name: Test Github workflow using self-hosted container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, rn-runner]
    container: 225237029829.dkr.ecr.eu-west-2.amazonaws.com/trunarrative/alpine:infra
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
